CREATE DATABASE xshop_ver3

USE xshop_ver3

CREATE TABLE categories (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	category_name VARCHAR(100) NOT NULL,
	slug VARCHAR(255) NOT NULL
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE products (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	product_name VARCHAR(100) NOT NULL,
	short_desc TEXT NOT NULL,
	unit_price DOUBLE NOT NULL,
	discount_percentage FLOAT NULL DEFAULT 0,
	main_img VARCHAR(255) NOT NULL,
	product_desc TEXT,
	category_id BIGINT NOT NULL 
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE colors (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	color_name VARCHAR(100) NOT NULL 
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE sizes (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	size_name VARCHAR(100) NOT NULL 
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE products_color (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	img VARCHAR(255) NOT NULL,
	color_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE products_size (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	product_color_id BIGINT NOT NULL,
	size_id BIGINT NOT NULL,
	remaining_quantity INT,
	sold_quantity INT
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE users (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	user_password VARCHAR(255) NOT NULL,
	phone VARCHAR(15) NOT NULL,
	user_role ENUM('admin', 'customer')
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE addresses (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	province VARCHAR(255) NOT NULL,
	district VARCHAR(255) NOT NULL,
	ward VARCHAR(255) NOT NULL,
	address_detail TEXT 
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE feedbacks (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	rating TINYINT NOT NULL,
	content TEXT
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE orders (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	payment_method ENUM('online', 'offline') NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	order_status TINYINT DEFAULT 1
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE orders_detail (
	order_id BIGINT NOT NULL,
	product_size_id BIGINT NOT NULL,
	quantity INT NOT NULL,
	PRIMARY KEY(order_id, product_size_id)
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE cart (
	user_id BIGINT NOT NULL,
	product_size_id BIGINT NOT NULL,
	quantity INT NOT NULL,
	PRIMARY KEY(user_id, product_size_id)
) AUTO_INCREMENT = 1, ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

ALTER TABLE products ADD FOREIGN KEY (category_id) REFERENCES categories(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE products_color ADD FOREIGN KEY (color_id) REFERENCES colors(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE products_color ADD FOREIGN KEY (product_id) REFERENCES products(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE products_size ADD FOREIGN KEY (size_id) REFERENCES sizes(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE products_size ADD FOREIGN KEY (product_color_id) REFERENCES products_color(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE feedbacks ADD FOREIGN KEY (user_id) REFERENCES users(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE feedbacks ADD FOREIGN KEY (product_id) REFERENCES products(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE addresses ADD FOREIGN KEY (user_id) REFERENCES users(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE orders ADD FOREIGN KEY (user_id) REFERENCES users(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE orders_detail ADD FOREIGN KEY (order_id) REFERENCES orders(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE orders_detail ADD FOREIGN KEY (product_size_id) REFERENCES products_size(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE cart ADD FOREIGN KEY (user_id) REFERENCES users(id)
ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE cart ADD FOREIGN KEY (product_size_id) REFERENCES products_size(id)
ON UPDATE CASCADE ON DELETE CASCADE
	